name: Deploy Auth service to Fly.io
on:
  # Runs on pushes for all branches
  push:
    branches:
      - "main"
    # Only runs for changes in the /auth directory
    paths:
      - "auth/**"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Auth Service
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd auth && flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
